# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Ремонт ОВК, ИО в ПМР. # the website title (if blank, full name will be used instead)
first_name: Kazachina
middle_name: al.
last_name: Alexei
email: alexei.kazachina@gmail.com
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Несколько страниц о Ремонте отопления вентиляции кондеционирования, искусственного охлаждения, контрольно измерительных приборов и автоматики в ПМР.
footer_text: >
  Powered by <a href="https://#" target="_blank">Jekyll</a> with <a href="https://github.com/alexei0kazachina">remont_ovk_io_pmr</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="" target="_blank">фото</a>.
keywords: jekyll, jekyll-theme, academic-website, portfolio-website  # add your own keywords or leave empty

lang: en, ru, ro # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)
# -----------------------------------------------------------------------------